name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # or windows-latest if you need a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This will checkout the code from GitHub

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Setup Buildx to allow multi-platform builds
      with:
        version: latest  # Optionally specify a version if needed, but default should be fine

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Log in to Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # Store username in GitHub Secrets
        password: ${{ secrets.DOCKERHUB_TOKEN }}  # Store password (token) in GitHub Secrets

    - name: Build Docker image
      run: |
        docker buildx build -t ${{ secrets.DOCKERHUB_USERNAME }}/call_api_from_requests:latest .  # Build Docker image using Buildx
    
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/call_api_from_requests:latest  # Push latest tag to Docker Hub
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/call_api_from_requests:${{ github.sha }}  # Push commit hash tag to Docker Hub

