name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   # Use 'ubuntu-latest' as the runner, you can also try 'windows-latest' if using Windows containers
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the code from GitHub

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for building multi-platform images

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Log in to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # Use Docker Hub username from Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}       # Use Docker Hub access token from Secrets

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4  # Action to build and push Docker images
        with:
          context: .   # Use the current directory as the build context
          push: true   # Push the image to Docker Hub
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/call_api_from_requests:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/call_api_from_requests:${{ github.sha }}  # Tag with commit SHA

      # Optional: If you have tests, you can add them here
      # - name: Run tests
      #   run: |
      #     pytest  # If you have tests set up
