name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Set to Ubuntu-based runner for Docker Buildx compatibility
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This will checkout the code from GitHub
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Logs into Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for building multi-platform images
      with:
        driver: buildx  # Set the Buildx driver to 'buildx'

    - name: Build Docker image
      run: |
        docker buildx build -t ${{ secrets.DOCKERHUB_USERNAME }}/call_api_from_requests:latest . --platform linux/amd64,linux/arm64 --push  # Build and push multi-platform image
    
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/call_api_from_requests:latest  # Push the latest tag
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/call_api_from_requests:${{ github.sha }}  # Push with commit hash tag
        
    # (Optional) Run tests if needed
    # - name: Run tests
    #   run: |
    #     pytest  # If you have tests set up
