name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false  # Disable push here, as we will push in a separate step
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/call_api_from_requests:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/call_api_from_requests:${{ github.sha }}

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true  # Enable push here
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/call_api_from_requests:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/call_api_from_requests:${{ github.sha }}
